[package]
name = "fulleffect"
version = "0.1.0"
authors = ["yoshi <ysnr.kdm@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
num = "*"
rand = "0.4.3"
rayon = "1.5"
time = "0.3.17"
getopts = "0.2"
stopwatch = "*"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
